/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Practica;

import javax.swing.JOptionPane;

/**
 *
 * @author calvo
 */
public class Ventana_Saludo extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Saludo
     */
    public Ventana_Saludo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_Confirmacion_Nombre = new javax.swing.JButton();
        Imagen_Saludo = new javax.swing.JLabel();
        Campo_Nombre = new javax.swing.JTextField();
        Texto_Apellido = new javax.swing.JLabel();
        Campo_Apellido = new javax.swing.JTextField();
        Texto_Nombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saludos!!");

        Boton_Confirmacion_Nombre.setText("Aceptar");
        Boton_Confirmacion_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Confirmacion_NombreActionPerformed(evt);
            }
        });

        Imagen_Saludo.setIcon(new javax.swing.ImageIcon("C:\\Users\\DAM2_09\\Documents\\GitHub\\pr-ctica-2-2-ventana-jframe-saludo-inicial-Willsongamf\\SOL\\Practica2-2\\src\\Practica\\saluda.png")); // NOI18N

        Campo_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_NombreActionPerformed(evt);
            }
        });

        Texto_Apellido.setText("Introduzca su apellido");

        Campo_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_ApellidoActionPerformed(evt);
            }
        });

        Texto_Nombre.setText("Introduzca su nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(Boton_Confirmacion_Nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Campo_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Texto_Apellido)
                            .addComponent(Texto_Nombre)
                            .addComponent(Campo_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Imagen_Saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagen_Saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Texto_Nombre)
                .addGap(18, 18, 18)
                .addComponent(Campo_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Texto_Apellido)
                .addGap(12, 12, 12)
                .addComponent(Campo_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Boton_Confirmacion_Nombre)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Campo_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_NombreActionPerformed


    }//GEN-LAST:event_Campo_NombreActionPerformed

    private void Boton_Confirmacion_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Confirmacion_NombreActionPerformed
        String nombre_completo = "Hola " + Campo_Nombre.getText() + " " + Campo_Apellido.getText();
        if (Campo_Nombre.getText().isEmpty() || Campo_Nombre.getText().length() < 5 || comprobar_Numero(Campo_Nombre.getText())) {
            JOptionPane.showMessageDialog(null, "Nombre  vacio, es menor de 5 caracteres o tiene numeros");
            return;
        }
        if (Campo_Apellido.getText().isEmpty() || Campo_Apellido.getText().length() < 5 || comprobar_Numero(Campo_Apellido.getText())) {
            JOptionPane.showMessageDialog(null, "Apellido vacio, es menor de 5 caracteres o tiene numeros");
            return;
        }
        JOptionPane.showMessageDialog(null, nombre_completo);
    }//GEN-LAST:event_Boton_Confirmacion_NombreActionPerformed

    public boolean comprobar_Numero(String entrada) {
        for (int i = 0; i < entrada.length(); i++) {
            if (entrada.charAt(i) >= 0 && entrada.charAt(i) <= 9) {
                return true;
            }
        }
        return false;
    }

    private void Campo_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_ApellidoActionPerformed

    }//GEN-LAST:event_Campo_ApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Saludo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Confirmacion_Nombre;
    private javax.swing.JTextField Campo_Apellido;
    private javax.swing.JTextField Campo_Nombre;
    private javax.swing.JLabel Imagen_Saludo;
    private javax.swing.JLabel Texto_Apellido;
    private javax.swing.JLabel Texto_Nombre;
    // End of variables declaration//GEN-END:variables
}
